/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "BBB_I2C.h"

#define US8 (uint8_t)
#define US8P (uint8_t*)
/* Header for class com_cacaosd_i2cjava_I2C */

#ifndef _Included_com_cacaosd_i2cjava_I2C
#define _Included_com_cacaosd_i2cjava_I2C
#ifdef __cplusplus

BBB_I2C i2c;
extern "C" {
#endif

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    setDeviceAddress
 * Signature: (B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_setDeviceAddress(JNIEnv *, jobject,
		jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    getDeviceAddress
 * Signature: ()B
 */
JNIEXPORT
jbyte JNICALL Java_com_cacaosd_i2cjava_I2C_getDeviceAddress(JNIEnv *, jobject);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    initialize
 * Signature: (B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_initialize(JNIEnv *, jobject, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeBit
 * Signature: (BBB)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeBit(JNIEnv *, jobject, jbyte,
		jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeBitNoExit
 * Signature: (BBB)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeBitNoExit(JNIEnv *, jobject,
		jbyte, jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeMoreBits
 * Signature: (BBBB)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeMoreBits(JNIEnv *, jobject,
		jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeMoreBitsNoExit
 * Signature: (BBBB)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeMoreBitsNoExit(JNIEnv *, jobject,
		jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByte
 * Signature: (BB)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByte(JNIEnv *, jobject, jbyte,
		jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByteNoExit
 * Signature: (BB)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByteNoExit(JNIEnv *, jobject,
		jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByteBuffer
 * Signature: (B[B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByteBuffer(JNIEnv *, jobject,
		jbyte, jbyteArray);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByteBufferNoExit
 * Signature: (B[B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByteBufferNoExit(JNIEnv *,
		jobject, jbyte, jbyteArray);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByteArduino
 * Signature: (B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByteArduino(JNIEnv *, jobject,
		jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByteArduinoNoExit
 * Signature: (B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByteArduinoNoExit(JNIEnv *,
		jobject, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByteBufferArduino
 * Signature: ([B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByteBufferArduino(JNIEnv *,
		jobject, jbyteArray);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    writeByteBufferArduinoNoExit
 * Signature: ([B)V
 */
JNIEXPORT
void JNICALL Java_com_cacaosd_i2cjava_I2C_writeByteBufferArduinoNoExit(JNIEnv *,
		jobject, jbyteArray);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readBit
 * Signature: (BB)B
 */
JNIEXPORT
jbyte JNICALL Java_com_cacaosd_i2cjava_I2C_readBit(JNIEnv *, jobject, jbyte,
		jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readBitNoExit
 * Signature: (BB)B
 */
JNIEXPORT
jbyte JNICALL Java_com_cacaosd_i2cjava_I2C_readBitNoExit(JNIEnv *, jobject,
		jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readMoreBits
 * Signature: (BBB)B
 */
JNIEXPORT
jbyte JNICALL Java_com_cacaosd_i2cjava_I2C_readMoreBits(JNIEnv *, jobject,
		jbyte, jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readMoreBitsNoExit
 * Signature: (BBB)B
 */
JNIEXPORT
jbyte JNICALL Java_com_cacaosd_i2cjava_I2C_readMoreBitsNoExit(JNIEnv *, jobject,
		jbyte, jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readByte
 * Signature: (B)B
 */
JNIEXPORT
jbyte JNICALL Java_com_cacaosd_i2cjava_I2C_readByte(JNIEnv *, jobject, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readByteNoExit
 * Signature: (B)B
 */
JNIEXPORT
jbyte JNICALL Java_com_cacaosd_i2cjava_I2C_readByteNoExit(JNIEnv *, jobject,
		jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readByteBuffer
 * Signature: (BB)[B
 */
JNIEXPORT
jbyteArray JNICALL Java_com_cacaosd_i2cjava_I2C_readByteBuffer(JNIEnv *,
		jobject, jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readByteBufferNoExit
 * Signature: (BB)[B
 */
JNIEXPORT
jbyteArray JNICALL Java_com_cacaosd_i2cjava_I2C_readByteBufferNoExit(JNIEnv *,
		jobject, jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readByteBufferArduino
 * Signature: (B)[B
 */
JNIEXPORT
jbyteArray JNICALL Java_com_cacaosd_i2cjava_I2C_readByteBufferArduino(JNIEnv *,
		jobject, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readByteBufferArduinoNoExit
 * Signature: (B)[B
 */
JNIEXPORT
jbyteArray JNICALL Java_com_cacaosd_i2cjava_I2C_readByteBufferArduinoNoExit(
		JNIEnv *, jobject, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readWord
 * Signature: (BB)[S
 */
JNIEXPORT
jshort JNICALL Java_com_cacaosd_i2cjava_I2C_readWord(JNIEnv *, jobject,
		jbyte, jbyte);

/*
 * Class:     com_cacaosd_i2cjava_I2C
 * Method:    readWordNoExit
 * Signature: (BB)[S
 */
JNIEXPORT
jshort JNICALL Java_com_cacaosd_i2cjava_I2C_readWordNoExit(JNIEnv *,
		jobject, jbyte, jbyte);

uint8_t DEV_ADD;
#ifdef __cplusplus
}
#endif
#endif

